// <auto-generated />
namespace FinalProject_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Quizs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Quizs));
        
        string IMigrationMetadata.Id
        {
            get { return "202106050831388_Quizs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
